services:
  gesturesensor:
    container_name: gesturesensor
    restart: unless-stopped
    image: gesturesensor:latest
    environment:
      - TZ=Asia/Ho_Chi_Minh  # Set your timezone here
    ports:
      - "1010:1010"  # Expose web UI port
    volumes:
      - ./config.yml:/config/config.yml:ro  # Mount your config file
      - ./storage:/app/storage  # Mount storage directory for saved images
    # Uncomment the following lines if you want to build the image directly
    # build:
    #   context: .
    #   dockerfile: Dockerfile
